### ISSUE TITLE
Google Material CSS file not found

### ISSUE THREAD

**Issue by ghost** [braginteractive/MDLWP#10]
I installed the WordPress theme, but when accessing the site you can see immediately that there is an css file missing. After checking the page's requests with the developer console shows that there is an error with this file:

http://storage.googleapis.com/code.getmdl.io/1.0.0/material.blue-grey-light_green.min.css?ver=4.3.1

![screen shot 2015-09-19 at 14 53 14](https://cloud.githubusercontent.com/assets/6087393/9976253/9aff4966-5ede-11e5-9ac4-bc141e3e7fd8.png)

The site looks like this:

![screen shot 2015-09-19 at 14 53 53](https://cloud.githubusercontent.com/assets/6087393/9976254/a05e2bf2-5ede-11e5-91cc-a7a794b83633.png)

I have no experience in developing WordPress themes, so I don't know how to fix that.

**Comment by braginteractive** [comment]
Probably just need to go into Appearance -> Customizer -> Colors and pick the primary and secondary colors you want to use.

**Comment by ghost** [comment]
That worked, thanks. But maybe you can fix it that it also works with the default (gray) color.
