### ISSUE TITLE
Hamburger menu icon

### ISSUE THREAD

**Issue by RocketUnlimited** [braginteractive/MDLWP#12]
On latest Samsung android default browser hamburger icon won't show up. Is there any fix for this?

**Comment by braginteractive** [comment]
Do the icons show up for you when viewing the MDL demos? http://www.getmdl.io/components/index.html#layout-section/layout

**Comment by RocketUnlimited** [comment]
No those don't appear either.

**Comment by braginteractive** [comment]
This needs to be reported to the MDL GitHub then: https://github.com/google/material-design-lite
