### ISSUE TITLE
clicking on site title not redirecting to the hompage 

### ISSUE THREAD

**Issue by pambreesh** [braginteractive/MDLWP#13]
the site logo title when clicked not redirecting to hompage which is very important for SEO . i think its not even hyperlinked .
Also not working on demopage here

http://mdlwp.com/demo/

**Comment by braginteractive** [comment]
You can edit templates/nav-man.php and wrap the title in a link if you would like.

**Comment by pambreesh** [comment]
Thanks you that worked fine, one more thing if u cud help for is that i want to know its body class for hompage only .thanks

**Comment by braginteractive** [comment]
I would recommend viewing the source code for your homepage to determine the different body classes.
