### ISSUE TITLE
Theme doesn't support dropdown menus

### ISSUE THREAD

**Issue by shanecarmody** [braginteractive/MDLWP#16]
I created a menu in **Appearance > Menus**, I then nested several menu items (see image below), but when I view the site it seems there is no support for dropdown menus in the theme. Am I missing something? Is this something that will be added down the line?

<img width="655" alt="capture d ecran 2016-02-01 a 16 07 17" src="https://cloud.githubusercontent.com/assets/433990/12721128/773ba2ce-c8fe-11e5-827c-8d74f84db987.png">

Thanks in advance.

**Comment by braginteractive** [comment]
This theme is based off the getmdl.io framework which currently doesn't have dropdown menus for main navigation links. Look over the navigation layouts: http://getmdl.io/components/index.html#layout-section/layout

**Comment by shanecarmody** [comment]
Okay, thanks for the info :+1:
