### ISSUE TITLE
Support for submenu

### ISSUE THREAD

**Issue by viankakrisna** [braginteractive/MDLWP#19]
Now it only print the submenu beside the parent menu. Maybe we can implement something like https://www.getmdl.io/components/index.html#menus-section, triggered on hover?

sub-menu in footer also broken:
![image](https://cloud.githubusercontent.com/assets/9636410/12866693/091773ee-cd0a-11e5-9c71-9e0f58d8c442.png)

**Comment by braginteractive** [comment]
MDL doesn't have dropdown menus for any of the navigation layouts https://www.getmdl.io/components/index.html#layout-section

This would be a feature request for MDL https://github.com/google/material-design-lite
