### ISSUE TITLE
Meta-box Customize in Custom Post Type

### ISSUE THREAD

**Issue by estudio3551** [braginteractive/MDLWP#20]
Can it be added the meta-box Customize a Custom post type? As it is shown in the post and pages.
Try editing the file 'meta-box.php' but I could not do it.

In line 21 I change this:
$screens = array( 'post', 'page' );

to this:
$screens = array( 'post', 'page', 'post_type' => 'name_custom_type' );

Thanks.

**Comment by braginteractive** [comment]
This is a MetaBox question, not a MDLWP issue. I would recommend looking over the MetaBox docs: https://metabox.io/docs/registering-meta-boxes/
