### ISSUE TITLE
WARN deprecated gulp-minify-css@1.2.4

### ISSUE THREAD

**Issue by claide** [braginteractive/MDLWP#23]
I tried to install dependencies but i got this line of message.
`npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
`

**Comment by braginteractive** [comment]
Install gulp-clean-css with NPM and then update the gulpfile.js file to use gulp-clean-css as the warning says. I will update the gulpfile the next time I do an update to the theme.
