### ISSUE TITLE
No option to add/change header image

### ISSUE THREAD

**Issue by Longthumb** [braginteractive/MDLWP#27]
I've added the following to header.php and I see no option within the Appearance settings to upload a header image. The option isn't in the customizer options either. Not sure what I'm doing wrong. Running MDLWP 1.2.2 on WP 4.5.1.

```
<?php if ( get_header_image() ) : ?>
<a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home">
    <img src="<?php header_image(); ?>" width="<?php echo esc_attr( get_custom_header()->width ); ?>" height="<?php echo esc_attr( get_custom_header()->height ); ?>" alt="">
</a>
<?php endif; // End header image check. ?>
```

**Comment by braginteractive** [comment]
This isn't an issue with the them, this is a customization. You need to implement it correctly for it to work. I would recommend check out the WP docs: https://codex.wordpress.org/Function_Reference/add_theme_support#Custom_Logo

**Comment by Longthumb** [comment]
Thanks for the help! Your theme is superb.
