### ISSUE TITLE
Menu Drawer list

### ISSUE THREAD

**Issue by yoyecros** [braginteractive/MDLWP#3]
If we have an element in the menu with some child, all are displayed inline without distinctions between parent and child. Can you make the drawer to display only parent with an arrow to "expand" the menu and to display child elements ? Or something like in https://www.google.com/design/spec/material-design/introduction.html ?
Thanks for your great job :)

**Comment by braginteractive** [comment]
MDL (http://www.getmdl.io/components/index.html#layout-section/layout) doesn't provide any styling for children menu items in both the main navigation and drawer right now. I plan to keep the theme an exact match of the functionality provided by MDL so there is no confusion. 

The MDL library is still very young, they have a lot of components and features to add. 

Until then, I would recommend checking out some of the other Material Design frameworks. They aren't the official Material Design library from Google, but they have a lot more features and components right now. 

I have created a few WP themes with them as well. You can find them at materialdesignthemes.com
