### ISSUE TITLE
masonry view broken

### ISSUE THREAD

**Issue by changethe** [braginteractive/MDLWP#33]
hey, I was going to use this theme, especially for the masonry view. unfortunately it gets displayed wrong in my browser most of the time.

sometimes it displays correctly (especially after going to a subpage and then using the back button of the browser to land back on the masonry view), but most of the times it gets displayed like in the screenshot.

I am running Mac OS X Yosemite and the latest google chrome.

<img width="1097" alt="screen shot 2016-10-12 at 21 09 52" src="https://cloud.githubusercontent.com/assets/7936889/19322183/b55b135c-90c0-11e6-8119-0371658ce407.png">

**Comment by braginteractive** [comment]
I have the same setup and it looks fine in my browser. Do you have any console errors? Have you tried other browsers?

**Comment by changethe** [comment]
ok, realized it only breaks when refreshing the page. sorry :)

https://jumpshare.com/v/HAziawbrlsUKCpEuJqk6
