### ISSUE TITLE
Material Design Portfolio

### ISSUE THREAD

**Issue by zaiats85** [braginteractive/MDLWP#36]
Hi
Recently bougth plugin works incorrectly. 
The issue is pretty much the same as been already discussed and left with no tech answer. 
Portfolio filter is totally random. 
May be you know already what is wrong.

**Comment by braginteractive** [comment]
I replied to your email. I am going to close this if there is already an issue open..

**Comment by zaiats85** [comment]
>Вторник, 17 января 2017, 17:55 +02:00 от Brad Williams <notifications@github.com>:
>
>Closed  #36 .
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

$('.portfolio').data('mixItUp').filter('.all')

Object initialized, methods available and do nothing. 

You r closing 3rd issue with no answer to the problem which really exist. Fact. 



Why?

**Comment by braginteractive** [comment]
Can you give me a little more detail? What browser, when you see the issue, etc?

**Comment by braginteractive** [comment]
In FF I am getting the following:

TypeError: n is null[Learn More] material.min.js:8:575
	e/< http://storage.googleapis.com/code.getmdl.io/1.0.4/material.min.js:8:575

I am going to try and update the theme to the latest version of MDL to see if that fixes the issue. 

It works in Chrome, but not in FF and Safari

**Comment by zaiats85** [comment]
in chrome :
tabs.js:131 Uncaught TypeError: Cannot read property 'classList' of null(…) . 

this comes from misuse of mdl tabs. not critical. I think the same with TypeError: n is null
Browser: chrome, safari, mozilla doesnt matter. the same problem.
Lib mixitup. Think the problem is there. Will try to debug. takes time

**Comment by zaiats85** [comment]
mdlwp-portfolio/includes/js/mdlwp-portfolio.js

**$('.tabs .categories-item a').click(function (e) {**
		e.preventDefault();
});
wrong selector

**Comment by zaiats85** [comment]
1) installed latest mixitup -3 from https://github.com/patrickkunka/mixitup
2) /mdlwp-portfolio/includes/js/mdlwp-portfolio.js 
scripts enqueued in head
        **wp_enqueue_script( 'mdlwp-portfolio-mixitup', $js_dir . 'mixitup.min.js', array('jquery'), 'false', false );
	wp_enqueue_script( 'mdlwp-portfolio', $js_dir . 'mdlwp-portfolio.js', array('jquery'), '1.0.0', false );**
3) /mdlwp-portfolio/archive-portfolio.php 
 - change div#primary class portfolio to smth. diff. (foobar)
- div.mdl-cell => remove 'all' from class name
4) /mdlwp-portfolio/includes/js/mdlwp-portfolio.js
-	**var mixer = $('.foobar').mixItUp();**
 -       $('.portfolio').mixItUp(); => remove
- $('.mdl-tabs a.categories-item').click(function (e) {
		e.preventDefault();
	}); =>  useless. 

Worked for me

**Comment by zaiats85** [comment]
for mdl card images to be available change  and minify the css file (new class foobar)

**Comment by braginteractive** [comment]
Nice work. Can you send me the files? I can also send you a refund for the plugin if you would like. Thanks

**Comment by zaiats85** [comment]
Sure. Will send files to your mail. No refund needed, customization made plugin more interesting. Global idea is great. Small implementation bugs.

**Comment by braginteractive** [comment]
Thank you.

**Comment by zaiats85** [comment]
sorry for late reply. Damn overload.
