### ISSUE TITLE
Registry returning 404

### ISSUE THREAD

**Issue by jromey** [braginteractive/MDLWP#39]
Running node -v v8.0.0
Running npm 5.0.3

npm ERR! code E404
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/mdlwp
npm ERR! 404 
npm ERR! 404  'mdlwp' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by braginteractive** [comment]
You try Googling the errors? This is NPM related not theme related..

https://stackoverflow.com/questions/11920571/cant-install-any-packages-in-node-js-using-npm-install

I am running NPM version 4.2.0 and Node v7.10.0 and didnt have any issues running `npm install`

**Comment by jromey** [comment]
Yes, this is indeed a npm issue.  I've since reverted back to v4.8.3.  thanks for your response!

**Comment by braginteractive** [comment]
No problem! Enjoy the theme.
