### ISSUE TITLE
Come MDL colors do not work

### ISSUE THREAD

**Issue by atais** [braginteractive/MDLWP#4]
Should be SOME MDL colors do not work sorry

If you want to customize your website color by choosing primary and secondary color the script tries to obtain the proper css from google.

For some colors though, the names are wrong and the css can not be downloaded.

I have found the code responsible:

``` php
$primary = get_theme_mod( 'primary_color', 'indigo' );
$secondary = get_theme_mod( 'secondary_color', 'pink' );

wp_enqueue_style( 'mdlwp-mdl-css', 'http://storage.googleapis.com/code.getmdl.io/1.0.2/material.min.css' );
```

I have modified it to obrain a standart css all the time. Normally it should use an url like:

`https://storage.googleapis.com/code.getmdl.io/1.0.2/material.*blue_grey*-amber.min.css`
but actually tries to resolve
`https://storage.googleapis.com/code.getmdl.io/1.0.2/material.*blue-grey*-amber.min.css`

**Comment by braginteractive** [comment]
Which colors aren't working?

**Comment by atais** [comment]
I wanted the one mentioned above (and it did not work) - blue_gray, but there were more. I can not check it now though.

**Comment by braginteractive** [comment]
I fixed the blue_grey color. Let me know if any of the other colors are not working.
