### ISSUE TITLE
Material Design Portfolio plugin

### ISSUE THREAD

**Issue by lili99** [braginteractive/MDLWP#43]
I like very match Material Design Portfolio plugin and I try to use in Divi. 
But I can't realise  that. 
Do you have any  idea if that maybe be  possible to work with Divi?
I am realy in love in this plugin.
Thank you very much advance .

Liliya

**Comment by braginteractive** [comment]
Liliya,

The plugin was built to work with MDLWP. It will not work with Divi. Divi doesn't have the Material Design Lite files that the plugin needs to work.

**Comment by lili99** [comment]
Thank you very much :-), I am glad for this alternative, I will try.

And all the best 

Liliya Zhekova
