### ISSUE TITLE
Footer is not a sticky type

### ISSUE THREAD

**Issue by atais** [braginteractive/MDLWP#7]
So i do not know if it is a bug or a feature but I would opt for the 1st one.

The problem occurs when the page you have is shorter than your browser height.

Looks like this:
![zrzut ekranu 2015-08-23 o 13 10 21](https://cloud.githubusercontent.com/assets/1538192/9427972/5c2266de-4998-11e5-96e1-250cb0a67e58.png)

So basically you can see the background of the main ribbon and the fotter is not at the bottom.
I am currently fixing it, so I will tell when I find a solution.

**Comment by atais** [comment]
I made it sticky with a simple css:

```css
 .mdl-mega-footer {
    position: absolute;
    bottom: 0;
    width: 100%
  }
```

But now I have a new issue when Wordpress bar comes in.

![zrzut ekranu 2015-08-23 o 13 43 56](https://cloud.githubusercontent.com/assets/1538192/9428076/6bbe529c-499d-11e5-9de9-167bac06cf69.png)

Currently I am clueless what can be done.

**Comment by braginteractive** [comment]
MDL doesn't provide any styles for a sticky footer (http://www.getmdl.io/components/index.html#layout-section/footer). This would be a customization. 

I am sure some people would like a PR on this if you figure something out.
