### ISSUE TITLE
Scrolling on iOS very sticky  

### ISSUE THREAD

**Issue by ghost** [braginteractive/MDLWP#8]
Hello.

Love the theme. I've been testing the theme on my main desktop and it works and looks amazing. However, when I tried testing it on my iPhone 6 the scrolling breaks after the page is fully loaded. The scrolling is very sticky and not smooth at all. 

Wondering if you would maybe look into this?

**Comment by braginteractive** [comment]
Does this happen on http://www.getmdl.io/ for you as well? 

The theme doesn't do any type of scroll jacking. It would have to be the MDL library

**Comment by ghost** [comment]
Sorry to report. The Google MDL templates work fine. There seems to be something interfering on the MDLWP theme, as the problem occurs on the demo site also.

**Comment by braginteractive** [comment]
I tested the site on a iPhone 6 Plus in the Safari app and didn't have any issues. I was able to navigate the whole demo site and scroll to the bottom of every page. 

Are you using something other than Safari? Maybe Chrome? Does it break in Safari for you?

**Comment by ghost** [comment]
I've attached a link to a video to demonstrate the problems I'm experiencing. 

https://photos.google.com/share/AF1QipN9eTMUOdUAGNI7pgzdDwrdUuaqkbAlEBjeB1RB_Gm0KRBos-bpT7vHk0dn2rYG-Q/photo/AF1QipN-2KBXyNp57mxok0c-sm_bfn5LNt8tf-13GqKl?key=NXU5NENwaXA5V2xsUjFxUWZsX1FtQTJpbkUzMHB3

**Comment by braginteractive** [comment]
Yeah, I see the same thing on my end. The scrolling isn't broken, but it isnt smooth either. 

Maybe related to this: 
https://github.com/google/material-design-lite/issues/925
https://github.com/google/material-design-lite/pull/730

**Comment by ghost** [comment]
I noticed you updated scripts.php to reflect the new changes to MDL. Not sure if this was included in the WP theme update or not, but my scripts were not updated to the latest version. I have went ahead and amended this and the scrolling issue was resolved.

**Comment by braginteractive** [comment]
Ah, I need to update the demo to the latest version. Glad this was sorted out.
